platform: linux
inputs:
- name: git-repo
outputs:
- name: triggers
run:
  path: bash
  args:
    - -exc
    - |
      ${PWD}/git-repo/ci/scripts/vscode-spring-cloud-dataflow-webview-flo-publish.sh
params:
  NPM_TOKEN_REPO_SPRING_IO: ((npm-token-repo-spring-io))
  NG_CLI_ANALYTICS: ci
